Repository prgrms-web-devcourse-final-project/WEB6_8_FiveLogic_BE, pull requests merged in 2025-09, with the labels that each got.

#2 chore: workflow 동작 테스트용 README 업데이트
  README.md
Labels: chore

#20 [Chore] 멘토링 관련 엔티티 구현
  back/src/main/java/com/back/domain/mentoring/mentoring/entity/Mentoring.java
  back/src/main/java/com/back/domain/mentoring/mentoring/entity/Review.java
  back/src/main/java/com/back/domain/mentoring/mentoring/repository/MentoRepository.java
  back/src/main/java/com/back/domain/mentoring/mentoring/repository/ReviewRepository.java
  back/src/main/java/com/back/domain/mentoring/reservation/constant/ReservationStatus.java
  back/src/main/java/com/back/domain/mentoring/reservation/entity/Reservation.java
  back/src/main/java/com/back/domain/mentoring/reservation/repository/ReservationRepository.java
  back/src/main/java/com/back/domain/mentoring/slot/constant/MentorSlotStatus.java
  back/src/main/java/com/back/domain/mentoring/slot/entity/MentorSlot.java
  back/src/main/java/com/back/domain/mentoring/slot/repository/MentorSlotRepository.java
Labels: chore

#21 [feat] 로드맵 도메인 엔티티 구현
  back/src/main/java/com/back/domain/job/job/entity/Job.java
  back/src/main/java/com/back/domain/job/job/entity/JobAlias.java
  back/src/main/java/com/back/domain/roadmap/roadmap/entity/JobRoadmap.java
  back/src/main/java/com/back/domain/roadmap/roadmap/entity/JobRoadmapNodeStat.java
  back/src/main/java/com/back/domain/roadmap/roadmap/entity/MentorRoadmap.java
  back/src/main/java/com/back/domain/roadmap/roadmap/entity/RoadmapNode.java
  back/src/main/java/com/back/domain/roadmap/task/entity/Task.java
  back/src/main/java/com/back/domain/roadmap/task/entity/TaskAlias.java
Labels: feat

#48 [feat] Task 기능 구현 완료
  back/src/main/java/com/back/domain/job/job/entity/JobAlias.java
  back/src/main/java/com/back/domain/job/job/repository/JobAliasRepository.java
  back/src/main/java/com/back/domain/job/job/repository/JobRepository.java
  back/src/main/java/com/back/domain/job/job/service/JobService.java
  back/src/main/java/com/back/domain/roadmap/task/controller/TaskController.java
  back/src/main/java/com/back/domain/roadmap/task/dto/CreatePendingAliasRequest.java
  back/src/main/java/com/back/domain/roadmap/task/dto/CreatePendingAliasResponse.java
  back/src/main/java/com/back/domain/roadmap/task/dto/LinkPendingAliasRequest.java
  back/src/main/java/com/back/domain/roadmap/task/dto/TaskAliasDetailDto.java
  back/src/main/java/com/back/domain/roadmap/task/dto/TaskAliasDto.java
  back/src/main/java/com/back/domain/roadmap/task/dto/TaskDto.java
  back/src/main/java/com/back/domain/roadmap/task/entity/TaskAlias.java
  back/src/main/java/com/back/domain/roadmap/task/repository/TaskAliasRepository.java
  back/src/main/java/com/back/domain/roadmap/task/repository/TaskRepository.java
  back/src/main/java/com/back/domain/roadmap/task/service/TaskService.java
  back/src/main/java/com/back/global/initData/RoadmapInitData.java
  back/src/test/java/com/back/domain/roadmap/task/controller/TaskControllerTest.java
  back/src/test/java/com/back/domain/roadmap/task/service/TaskServiceTest.java
Labels: feat

#52 Feat#36 댓글 CRUID 기능 구현
  back/src/main/java/com/back/domain/post/comment/controller/PostCommentController.java
  back/src/main/java/com/back/domain/post/comment/dto/CommentAllResponse.java
  back/src/main/java/com/back/domain/post/comment/dto/CommentCreateRequest.java
  back/src/main/java/com/back/domain/post/comment/dto/CommentDeleteRequest.java
  back/src/main/java/com/back/domain/post/comment/dto/CommentModifyRequest.java
  back/src/main/java/com/back/domain/post/comment/service/PostCommentService.java
  back/src/main/java/com/back/domain/post/post/controller/InformationPostController.java
  back/src/main/java/com/back/global/init/PostInitData.java
  back/src/main/java/com/back/global/security/CustomAuthenticationFilter.java
  back/src/test/java/com/back/domain/post/comment/PostCommentControllerTest.java
Labels: feat

#74 chore:swagger문서
  back/src/main/java/com/back/domain/member/member/controller/MemberController.java
Labels: chore

#76 [Refactor] Task 도메인 수정
  back/src/main/java/com/back/domain/roadmap/task/controller/TaskController.java
  back/src/main/java/com/back/domain/roadmap/task/entity/Task.java
  back/src/main/java/com/back/domain/roadmap/task/entity/TaskAlias.java
  back/src/main/java/com/back/domain/roadmap/task/service/TaskService.java
  back/src/test/java/com/back/domain/roadmap/task/controller/TaskControllerTest.java
  back/src/test/java/com/back/domain/roadmap/task/service/TaskServiceTest.java
Labels: refactor

#79 파일업로드 및 트랜스코딩 파이프라인 작성
  Dockerfile
  back/src/main/java/com/back/domain/file/controller/VideoController.java
  back/src/main/java/com/back/domain/file/service/VideoService.java
  back/src/main/java/com/back/global/app/S3Config.java
  back/src/main/java/com/back/global/security/SecurityConfig.java
  consumer.py
  docker-compose.yml
  requirements.txt
Labels: feat

#91 Refactor Setter 제거 - Builder 방식으로 객체 성성
  back/src/main/java/com/back/domain/post/comment/entity/PostComment.java
  back/src/main/java/com/back/domain/post/comment/service/PostCommentService.java
  back/src/main/java/com/back/domain/post/post/entity/Post.java
  back/src/main/java/com/back/domain/post/post/service/PostService.java
  back/src/main/java/com/back/global/initData/PostInitData.java
Labels: refactor

#95 [Refactor] 멘토링 연관 도메인에 MentoringStorage, MemberStorage 적용
  back/src/main/java/com/back/domain/member/member/service/MemberStorage.java
  back/src/main/java/com/back/domain/mentoring/mentoring/controller/MentoringController.java
  back/src/main/java/com/back/domain/mentoring/mentoring/service/MentoringService.java
  back/src/main/java/com/back/domain/mentoring/mentoring/service/MentoringStorage.java
  back/src/main/java/com/back/domain/mentoring/reservation/controller/ReservationController.java
  back/src/main/java/com/back/domain/mentoring/slot/controller/MentorSlotController.java
  back/src/main/java/com/back/domain/mentoring/slot/service/MentorSlotService.java
  back/src/test/java/com/back/domain/mentoring/mentoring/controller/MentoringControllerTest.java
Labels: refactor

#96 [Feat] 멘토 로드맵 CRUD
  back/src/main/java/com/back/domain/roadmap/roadmap/controller/MentorRoadmapController.java
  back/src/main/java/com/back/domain/roadmap/roadmap/dto/request/MentorRoadmapSaveRequest.java
  back/src/main/java/com/back/domain/roadmap/roadmap/dto/request/RoadmapNodeRequest.java
  back/src/main/java/com/back/domain/roadmap/roadmap/dto/response/MentorRoadmapResponse.java
  back/src/main/java/com/back/domain/roadmap/roadmap/dto/response/MentorRoadmapSaveResponse.java
  back/src/main/java/com/back/domain/roadmap/roadmap/dto/response/RoadmapNodeResponse.java
  back/src/main/java/com/back/domain/roadmap/roadmap/entity/JobRoadmap.java
  back/src/main/java/com/back/domain/roadmap/roadmap/entity/MentorRoadmap.java
  back/src/main/java/com/back/domain/roadmap/roadmap/entity/RoadmapNode.java
  back/src/main/java/com/back/domain/roadmap/roadmap/repository/MentorRoadmapRepository.java
  back/src/main/java/com/back/domain/roadmap/roadmap/repository/RoadmapNodeRepository.java
  back/src/main/java/com/back/domain/roadmap/roadmap/service/MentorRoadmapService.java
  back/src/test/java/com/back/domain/roadmap/roadmap/service/MentorRoadmapServiceTest.java
Labels: feat

#101 [Refactor] 예약 동시성 고려
  back/src/main/java/com/back/domain/mentoring/reservation/entity/Reservation.java
  back/src/main/java/com/back/domain/mentoring/reservation/error/ReservationErrorCode.java
  back/src/main/java/com/back/domain/mentoring/reservation/repository/ReservationRepository.java
  back/src/main/java/com/back/domain/mentoring/reservation/service/ReservationService.java
  back/src/main/java/com/back/domain/mentoring/slot/entity/MentorSlot.java
  back/src/test/java/com/back/domain/mentoring/mentoring/controller/MentoringControllerTest.java
  back/src/test/java/com/back/domain/mentoring/reservation/controller/ReservationControllerTest.java
  back/src/test/java/com/back/domain/mentoring/slot/controller/MentorSlotControllerTest.java
  back/src/test/java/com/back/fixture/MentoringTestFixture.java
Labels: refactor

#105 [Refactor] 검증 로직 수정
  back/src/main/java/com/back/domain/roadmap/roadmap/controller/MentorRoadmapController.java
  back/src/main/java/com/back/domain/roadmap/roadmap/dto/response/MentorRoadmapResponse.java
  back/src/main/java/com/back/domain/roadmap/roadmap/dto/response/MentorRoadmapSaveResponse.java
  back/src/main/java/com/back/domain/roadmap/roadmap/dto/response/RoadmapNodeResponse.java
  back/src/main/java/com/back/domain/roadmap/roadmap/entity/MentorRoadmap.java
  back/src/main/java/com/back/domain/roadmap/roadmap/entity/RoadmapNode.java
  back/src/main/java/com/back/domain/roadmap/roadmap/repository/MentorRoadmapRepository.java
  back/src/main/java/com/back/domain/roadmap/roadmap/repository/RoadmapNodeRepository.java
  back/src/main/java/com/back/domain/roadmap/roadmap/service/MentorRoadmapService.java
  back/src/test/java/com/back/domain/roadmap/roadmap/service/MentorRoadmapServiceTest.java
Labels: refactor

#110 [refactor] Job 도메인 엔티티 @Setter 제거
  back/src/main/java/com/back/domain/job/job/entity/Job.java
  back/src/main/java/com/back/domain/job/job/entity/JobAlias.java
  back/src/main/java/com/back/domain/job/job/service/JobService.java
Labels: refactor

#125 [Feat] 예약 확정/취소/변경
  back/src/main/java/com/back/domain/member/member/service/MemberStorage.java
  back/src/main/java/com/back/domain/mentoring/mentoring/service/MentoringStorage.java
  back/src/main/java/com/back/domain/mentoring/reservation/constant/ReservationStatus.java
  back/src/main/java/com/back/domain/mentoring/reservation/controller/ReservationController.java
  back/src/main/java/com/back/domain/mentoring/reservation/entity/Reservation.java
  back/src/main/java/com/back/domain/mentoring/reservation/error/ReservationErrorCode.java
  back/src/main/java/com/back/domain/mentoring/reservation/service/ReservationService.java
  back/src/main/java/com/back/domain/mentoring/slot/entity/MentorSlot.java
  back/src/test/java/com/back/domain/mentoring/mentoring/controller/MentoringControllerTest.java
  back/src/test/java/com/back/domain/mentoring/reservation/controller/ReservationControllerTest.java
  back/src/test/java/com/back/domain/mentoring/reservation/entity/ReservationTest.java
  back/src/test/java/com/back/domain/mentoring/reservation/service/ReservationServiceTest.java
  back/src/test/java/com/back/domain/mentoring/slot/controller/MentorSlotControllerTest.java
  back/src/test/java/com/back/domain/mentoring/slot/service/MentorSlotServiceTest.java
  back/src/test/java/com/back/fixture/mentoring/MentorSlotFixture.java
  back/src/test/java/com/back/fixture/mentoring/MentoringTestFixture.java
  back/src/test/java/com/back/fixture/mentoring/ReservationFixture.java
Labels: feat

#127 Feat: 직업 로드맵 조회 api 구현
  back/src/main/java/com/back/domain/roadmap/roadmap/controller/JobRoadmapController.java
  back/src/main/java/com/back/domain/roadmap/roadmap/dto/response/JobRoadmapListResponse.java
  back/src/main/java/com/back/domain/roadmap/roadmap/dto/response/JobRoadmapNodeResponse.java
  back/src/main/java/com/back/domain/roadmap/roadmap/dto/response/JobRoadmapPagingResponse.java
  back/src/main/java/com/back/domain/roadmap/roadmap/dto/response/JobRoadmapResponse.java
  back/src/main/java/com/back/domain/roadmap/roadmap/entity/JobRoadmap.java
  back/src/main/java/com/back/domain/roadmap/roadmap/entity/JobRoadmapNodeStat.java
  back/src/main/java/com/back/domain/roadmap/roadmap/entity/MentorRoadmap.java
  back/src/main/java/com/back/domain/roadmap/roadmap/entity/RoadmapNode.java
  back/src/main/java/com/back/domain/roadmap/roadmap/repository/JobRoadmapRepository.java
  back/src/main/java/com/back/domain/roadmap/roadmap/repository/MentorRoadmapRepository.java
  back/src/main/java/com/back/domain/roadmap/roadmap/service/JobRoadmapService.java
  back/src/main/java/com/back/global/initData/RoadmapInitData.java
  back/src/test/java/com/back/domain/roadmap/roadmap/controller/JobRoadmapControllerTest.java
  back/src/test/java/com/back/domain/roadmap/roadmap/service/JobRoadmapServiceTest.java
Labels: feat
